// ============================================================
// TrueMargin — UI Copy Constants
// All user-facing strings live here for easy updates.
// ============================================================

export const COPY = {
  // Brand
  APP_NAME: "TrueMargin",
  TAGLINE: "Know your margin before the job ends.",

  // Auth
  LOGIN_TITLE: "Sign in to TrueMargin",
  LOGIN_SUBTITLE: "Track your job margins in real time.",
  SIGNUP_TITLE: "Create your TrueMargin account",
  SIGNUP_SUBTITLE: "Start your 14-day free trial — no credit card required.",
  EMAIL_LABEL: "Email address",
  PASSWORD_LABEL: "Password",
  FULL_NAME_LABEL: "Full name",
  LOGIN_BUTTON: "Sign in",
  SIGNUP_BUTTON: "Create account",
  FORGOT_PASSWORD: "Forgot your password?",
  NO_ACCOUNT: "Don't have an account?",
  HAS_ACCOUNT: "Already have an account?",

  // Navigation
  NAV_DASHBOARD: "Dashboard",
  NAV_JOBS: "Jobs",
  NAV_REPORTS: "Reports",
  NAV_SETTINGS: "Settings",
  NAV_TEAM: "Team",
  NAV_BILLING: "Billing",
  NAV_LOGOUT: "Sign out",

  // Dashboard
  DASHBOARD_TITLE: "Dashboard",
  ACTIVE_JOBS: "Active Jobs",
  AT_RISK_JOBS: "At-Risk Jobs",
  AVG_MARGIN: "Avg. Margin This Month",
  NEW_JOB: "New Job",

  // Jobs
  JOBS_TITLE: "Jobs",
  JOB_NAME: "Job name",
  CUSTOMER_NAME: "Customer name",
  CUSTOMER_ADDRESS: "Customer address",
  JOB_TYPE: "Job type",
  CONTRACT_VALUE: "Contract value (CAD)",
  LABOUR_HOURS: "Labour hours",
  LABOUR_RATE: "Labour rate (CAD/hr)",
  MATERIALS_ESTIMATE: "Materials estimate (CAD)",
  SUBCONTRACTOR_ESTIMATE: "Subcontractor estimate (CAD)",
  OVERHEAD_RATE: "Overhead rate (%)",
  NOTES: "Notes",
  CREATE_JOB: "Create Job",
  ESTIMATED_COST: "Estimated Cost",
  ESTIMATED_PROFIT: "Estimated Gross Profit",
  ESTIMATED_MARGIN: "Estimated Margin",
  CURRENT_MARGIN: "current margin",
  ACTUAL_COST: "Actual Cost",
  VARIANCE: "Over/Under Budget",
  EDIT_JOB: "Edit Job",
  SAVE_JOB: "Save Changes",
  DELETE_COST_ENTRY: "Delete Entry",
  DELETE_COST_CONFIRM: "Are you sure you want to delete this cost entry? This cannot be undone.",
  STATUS_CHANGE_CONFIRM: "Are you sure you want to change this job's status?",
  COST_BREAKDOWN_TITLE: "Cost Breakdown by Category",
  ESTIMATED_VS_ACTUAL: "Estimated vs. Actual",
  SEARCH_JOBS: "Search jobs…",
  EXPORT_CSV: "Export CSV",
  OVERHEAD_TOOLTIP: "Covers office, insurance, vehicle, and admin costs not directly billed to the job.",
  WORST_JOB_TITLE: "Needs Attention",
  MARGIN_TREND_UP: "up from last month",
  MARGIN_TREND_DOWN: "down from last month",
  MARGIN_TREND_SAME: "same as last month",

  // Status
  STATUS_ON_TRACK: "On Track",
  STATUS_AT_RISK: "At Risk",
  STATUS_OVER_BUDGET: "Over Budget",
  STATUS_ESTIMATING: "Estimating",
  STATUS_ACTIVE: "Active",
  STATUS_ON_HOLD: "On Hold",
  STATUS_CLOSED: "Closed",

  // Job Types
  JOB_TYPE_HVAC_INSTALL: "HVAC Install",
  JOB_TYPE_HVAC_SERVICE: "HVAC Service",
  JOB_TYPE_PLUMBING: "Plumbing",
  JOB_TYPE_ELECTRICAL: "Electrical",
  JOB_TYPE_ROOFING: "Roofing",
  JOB_TYPE_FLOORING: "Flooring",
  JOB_TYPE_PAINTING: "Painting",
  JOB_TYPE_LANDSCAPING: "Landscaping",
  JOB_TYPE_CONCRETE: "Concrete",
  JOB_TYPE_FRAMING: "Framing",
  JOB_TYPE_DRYWALL: "Drywall",
  JOB_TYPE_INSULATION: "Insulation",
  JOB_TYPE_SIDING: "Siding",
  JOB_TYPE_WINDOWS_DOORS: "Windows & Doors",
  JOB_TYPE_DEMOLITION: "Demolition",
  JOB_TYPE_BATHROOM_RENO: "Bathroom Renovation",
  JOB_TYPE_KITCHEN_RENO: "Kitchen Renovation",
  JOB_TYPE_BASEMENT_FINISHING: "Basement Finishing",
  JOB_TYPE_DECK_FENCE: "Deck & Fence",
  JOB_TYPE_GENERAL_RENOVATION: "General Renovation",
  JOB_TYPE_FIRE_RESTORATION: "Fire Restoration",
  JOB_TYPE_WATERPROOFING: "Waterproofing",
  JOB_TYPE_EXCAVATION: "Excavation",
  JOB_TYPE_TILE_MASONRY: "Tile & Masonry",
  JOB_TYPE_CARPENTRY: "Carpentry",
  JOB_TYPE_GARAGE_DOOR: "Garage Door",
  JOB_TYPE_SOLAR: "Solar",
  JOB_TYPE_OTHER: "Other",

  // Cost Feed
  COST_FEED_TITLE: "Cost Entries",
  ADD_COST_ENTRY: "Add Entry",
  COST_CATEGORY: "Category",
  COST_DESCRIPTION: "Description",
  COST_AMOUNT: "Amount (CAD)",
  SOURCE_SMS: "SMS",
  SOURCE_MANUAL: "Manual",
  SOURCE_IMPORT: "Import",

  // Change Orders
  CHANGE_ORDER_TITLE: "Change Order",
  NEW_CHANGE_ORDER: "New Change Order",
  CO_TITLE: "Title",
  CO_DESCRIPTION: "Description",
  CO_AMOUNT: "Amount (CAD)",
  CO_PHOTO: "Photo (optional)",
  CO_APPROVE: "I approve this change order",
  CO_SIGNED_BY: "Approved by",

  // Settings
  SETTINGS_TITLE: "Company Settings",
  COMPANY_NAME: "Company name",
  COMPANY_PHONE: "Company phone",
  COMPANY_ADDRESS: "Company address",
  PROVINCE: "Province",
  TAX_NUMBER: "HST/GST registration number",
  DEFAULT_LABOUR_RATE: "Default labour rate (CAD/hr)",
  DEFAULT_OVERHEAD: "Default overhead rate (%)",
  SAVE_SETTINGS: "Save Changes",

  // Team
  TEAM_TITLE: "Team Members",
  TEAM_SUBTITLE: "Manage your team and invite new members.",
  INVITE_MEMBER: "Invite Team Member",
  INVITE_SEND: "Send Invite",
  INVITE_SENDING: "Sending...",
  INVITE_SUCCESS: "Invite sent successfully!",
  INVITE_PENDING: "Pending Invites",
  INVITE_NO_PENDING: "No pending invites.",
  INVITE_SENT_TO: "Invite sent to",
  INVITE_EXPIRES: "Expires",
  INVITE_RESEND: "Resend",
  INVITE_REVOKE: "Revoke",
  INVITE_ACCEPT_TITLE: "You've been invited to join",
  INVITE_ACCEPT_SUBTITLE: "Create an account or sign in to accept this invite.",
  INVITE_ACCEPT_BUTTON: "Accept Invite",
  INVITE_ACCEPTING: "Accepting...",
  INVITE_ACCEPTED: "You're in! Redirecting to dashboard...",
  INVITE_EXPIRED: "This invite has expired.",
  INVITE_INVALID: "This invite is invalid or has been revoked.",
  INVITE_EMAIL_MISMATCH: "Please sign in with the email this invite was sent to.",
  ROLE_OWNER: "Owner",
  ROLE_PM: "Project Manager",
  ROLE_CREW_LEAD: "Crew Lead",
  MEMBER_ACTIVE: "Active",
  MEMBER_INACTIVE: "Inactive",
  MEMBER_DEACTIVATE: "Deactivate",
  MEMBER_REACTIVATE: "Reactivate",
  MEMBER_CHANGE_ROLE: "Change Role",
  MEMBER_NO_MEMBERS: "No team members yet. Send an invite to get started.",
  MEMBER_ONLY_OWNER: "Only the account owner can manage team members.",

  // Billing
  BILLING_TITLE: "Billing & Subscription",
  MANAGE_SUBSCRIPTION: "Manage Subscription",
  CURRENT_PLAN: "Current Plan",
  PLAN_STARTER: "Starter",
  PLAN_GROWTH: "Growth",
  PLAN_SCALE: "Scale",
  BILLING_SUBTITLE: "Manage your TrueMargin subscription and billing details.",
  PLAN_MONTHLY: "/month CAD",
  PLAN_TRIAL_BADGE: "14-day free trial",
  PLAN_CURRENT_BADGE: "Current plan",
  PLAN_POPULAR_BADGE: "Most popular",
  PLAN_SELECT: "Get started",
  PLAN_UPGRADE: "Upgrade",
  PLAN_DOWNGRADE: "Downgrade",
  PLAN_MANAGE: "Manage Billing",
  SUBSCRIPTION_ACTIVE: "Active",
  SUBSCRIPTION_TRIALING: "Trial",
  SUBSCRIPTION_PAST_DUE: "Past Due",
  SUBSCRIPTION_CANCELED: "Canceled",
  BILLING_PORTAL_DESC: "Update your payment method, download invoices, or cancel your subscription.",
  BILLING_NO_SUBSCRIPTION: "You don't have an active subscription. Choose a plan below to get started.",
  BILLING_PAST_DUE_WARNING: "Your payment is past due. Please update your payment method to avoid service interruption.",
  BILLING_CANCELED_WARNING: "Your subscription has been canceled. Choose a plan below to resubscribe.",

  // Reports
  REPORTS_TITLE: "Reports",
  REPORTS_SUBTITLE: "Margin performance across your jobs.",
  REPORTS_MARGIN_BY_MONTH: "Margin by Month",
  REPORTS_MARGIN_BY_TYPE: "Margin by Job Type",
  REPORTS_JOB_SUMMARY: "Job Summary",
  REPORTS_TOTAL_REVENUE: "Total Revenue",
  REPORTS_TOTAL_COST: "Total Cost",
  REPORTS_TOTAL_PROFIT: "Total Profit",
  REPORTS_AVG_MARGIN: "Avg. Margin",
  REPORTS_NO_DATA: "No completed jobs to report on yet. Close a job to see margin data here.",
  REPORTS_PERIOD_THIS_MONTH: "This Month",
  REPORTS_PERIOD_LAST_3: "Last 3 Months",
  REPORTS_PERIOD_LAST_6: "Last 6 Months",
  REPORTS_PERIOD_THIS_YEAR: "This Year",
  REPORTS_PERIOD_ALL_TIME: "All Time",

  // SMS
  SMS_SUCCESS: "✓ ${amount} ${category} logged on ${jobCode}. Job margin: ${margin}% (${status})",
  SMS_UNKNOWN_USER:
    "TrueMargin: Your number isn't linked to an account. Ask your PM to add you.",
  SMS_PARSE_ERROR:
    "Couldn't read that. Try: 'JOB-4821 materials 340 copper pipe'. Reply HELP for examples.",
  SMS_HELP:
    "TrueMargin SMS commands:\n• materials 340 copper pipe\n• labour 4hrs\n• sub 850 electrical rough in\n• equip 200 rental\n• JOB-XXXX materials 340 pipe\n• start (clock in)\n• stop (clock out)\n\nInclude a job code if you have multiple active jobs.",

  // OCR / Invoice Scanning
  OCR_TITLE: "Scan Invoice",
  OCR_SUBTITLE: "Upload a receipt or supplier invoice to auto-extract line items.",
  OCR_UPLOAD: "Upload Invoice",
  OCR_UPLOADING: "Uploading…",
  OCR_PROCESSING: "Processing invoice…",
  OCR_COMPLETED: "Line items extracted",
  OCR_FAILED: "Could not read this document. Try a clearer photo.",
  OCR_DRAG_DROP: "Drag & drop an invoice, or click to browse",
  OCR_SUPPORTED: "Supports JPG, PNG, PDF (max 10MB)",
  OCR_REVIEW_ITEMS: "Review Extracted Items",
  OCR_CONFIRM_ALL: "Add All to Job",
  OCR_CONFIRM_SELECTED: "Add Selected",
  OCR_LOW_CONFIDENCE: "Low confidence — please verify",
  OCR_NO_ITEMS: "No line items could be extracted from this document.",

  // Cost Validation
  VALIDATION_PENDING: "Pending Review",
  VALIDATION_VALIDATED: "Validated",
  VALIDATION_REJECTED: "Rejected",
  VALIDATION_APPROVE: "Approve",
  VALIDATION_REJECT: "Reject",
  VALIDATION_APPROVE_ALL: "Approve All Pending",
  VALIDATION_PENDING_COUNT: "pending review",
  VALIDATION_SUMMARY: "Cost Validation",

  // Time Tracking
  TIME_TRACKING_TITLE: "Time Tracking",
  TIME_CLOCK_IN: "Clock In",
  TIME_CLOCK_OUT: "Clock Out",
  TIME_ACTIVE: "Active Timer",
  TIME_NO_ACTIVE: "No active timer",
  TIME_HISTORY: "Time Log",
  TIME_HOURS: "hours",
  TIME_STARTED: "Started",
  TIME_STOPPED: "Stopped",
  TIME_DURATION: "Duration",
  TIME_SMS_CLOCKED_IN: "✓ Clocked in on ${jobCode} at ${time}. Text 'stop' when done.",
  TIME_SMS_CLOCKED_OUT: "✓ Clocked out on ${jobCode}. ${hours}h logged = $${amount}. Job margin: ${margin}% (${status})",
  TIME_SMS_ALREADY_CLOCKED_IN: "You're already clocked in on ${jobCode}. Text 'stop' to clock out first.",
  TIME_SMS_NOT_CLOCKED_IN: "You're not clocked in. Text 'start' to begin tracking time.",

  // Benchmarking
  BENCHMARK_TITLE: "Industry Comparison",
  BENCHMARK_SUBTITLE: "See how your margins compare to similar jobs.",
  BENCHMARK_YOUR_MARGIN: "Your Avg. Margin",
  BENCHMARK_INDUSTRY_AVG: "Industry Avg.",
  BENCHMARK_PERCENTILE: "Percentile",
  BENCHMARK_SAMPLE_SIZE: "Based on",
  BENCHMARK_JOBS: "jobs",
  BENCHMARK_NO_DATA: "Not enough data for benchmarks yet.",
  BENCHMARK_ABOVE_AVG: "Above average",
  BENCHMARK_BELOW_AVG: "Below average",

  // Customer Portal
  PORTAL_TITLE: "Job Progress",
  PORTAL_SUBTITLE: "Real-time updates on your project.",
  PORTAL_SHARE_LINK: "Share Customer Portal",
  PORTAL_COPY_LINK: "Copy Link",
  PORTAL_LINK_COPIED: "Link copied!",
  PORTAL_PROGRESS: "Progress",
  PORTAL_BALANCE: "Balance Remaining",
  PORTAL_CHANGE_ORDERS: "Change Orders",
  PORTAL_POWERED_BY: "Powered by TrueMargin",
  PORTAL_STATUS_LABEL: "Project Status",

  // Estimate Line Items
  LINE_ITEMS_TITLE: "Estimate Line Items",
  ADD_LINE_ITEM: "Add Line Item",
  LINE_ITEM_DESCRIPTION: "Description",
  LINE_ITEM_QUANTITY: "Qty",
  LINE_ITEM_UNIT: "Unit",
  LINE_ITEM_UNIT_PRICE: "Unit Price",
  LINE_ITEM_TOTAL: "Total",
  LINE_ITEM_CATEGORY: "Category",
  LINE_ITEM_PHASE: "Phase",
  LINE_ITEM_VENDOR: "Vendor",
  LINE_ITEM_EMPTY: "No line items yet. Add items to build your estimate.",
  LINE_ITEM_SEARCH_HINT: "Type to search or enter custom…",

  // Job Phases
  PHASES_TITLE: "Job Phases",
  ADD_PHASE: "Add Phase",
  PHASE_NAME: "Phase name",
  PHASE_STATUS_PENDING: "Pending",
  PHASE_STATUS_IN_PROGRESS: "In Progress",
  PHASE_STATUS_COMPLETED: "Completed",
  LOAD_TEMPLATE_PHASES: "Load Template Phases",

  // Vendors
  VENDOR_NAME: "Vendor / Supplier",
  VENDOR_SEARCH_HINT: "Search or add vendor…",
  VENDOR_CATEGORY_SUPPLIER: "Supplier",
  VENDOR_CATEGORY_SUBCONTRACTOR: "Subcontractor",
  VENDOR_CATEGORY_EQUIPMENT_RENTAL: "Equipment Rental",
  VENDOR_CATEGORY_OTHER: "Other",

  // Cost Entry (additional fields)
  COST_QUANTITY: "Quantity",
  COST_UNIT: "Unit",
  COST_UNIT_PRICE: "Unit Price",
  COST_VENDOR: "Vendor",

  // Misc
  LOADING: "Loading...",
  NO_DATA: "No data yet.",
  ERROR_GENERIC: "Something went wrong. Please try again.",
  CURRENCY: "CAD",
  SAVE: "Save",
  CANCEL: "Cancel",
  DELETE: "Delete",
  EDIT: "Edit",
  BACK: "Back",

  // Cost entry editing & receipts
  EDIT_ENTRY: "Edit Entry",
  SAVE_ENTRY: "Save Changes",
  EDITING_ENTRY: "Saving…",
  ATTACH_RECEIPT: "Attach Receipt",
  UPLOAD_RECEIPT: "Upload Receipt",
  UPLOADING_RECEIPT: "Uploading…",
  RECEIPT_LABEL: "Receipt",
  VIEW_RECEIPT: "View Receipt",
  REMOVE_RECEIPT: "Remove Receipt",
  RECEIPT_FORMATS: "JPG, PNG, WebP, or PDF (max 10MB)",
} as const;

// Province options for select dropdown
export const PROVINCE_OPTIONS: ReadonlyArray<{
  value: string;
  label: string;
}> = [
  { value: "AB", label: "Alberta" },
  { value: "BC", label: "British Columbia" },
  { value: "MB", label: "Manitoba" },
  { value: "NB", label: "New Brunswick" },
  { value: "NL", label: "Newfoundland and Labrador" },
  { value: "NS", label: "Nova Scotia" },
  { value: "NT", label: "Northwest Territories" },
  { value: "NU", label: "Nunavut" },
  { value: "ON", label: "Ontario" },
  { value: "PE", label: "Prince Edward Island" },
  { value: "QC", label: "Quebec" },
  { value: "SK", label: "Saskatchewan" },
  { value: "YT", label: "Yukon" },
] as const;

// Job type options for select dropdown
export const JOB_TYPE_OPTIONS: ReadonlyArray<{
  value: string;
  label: string;
}> = [
  { value: "hvac_install", label: COPY.JOB_TYPE_HVAC_INSTALL },
  { value: "hvac_service", label: COPY.JOB_TYPE_HVAC_SERVICE },
  { value: "plumbing", label: COPY.JOB_TYPE_PLUMBING },
  { value: "electrical", label: COPY.JOB_TYPE_ELECTRICAL },
  { value: "roofing", label: COPY.JOB_TYPE_ROOFING },
  { value: "flooring", label: COPY.JOB_TYPE_FLOORING },
  { value: "painting", label: COPY.JOB_TYPE_PAINTING },
  { value: "landscaping", label: COPY.JOB_TYPE_LANDSCAPING },
  { value: "concrete", label: COPY.JOB_TYPE_CONCRETE },
  { value: "framing", label: COPY.JOB_TYPE_FRAMING },
  { value: "drywall", label: COPY.JOB_TYPE_DRYWALL },
  { value: "insulation", label: COPY.JOB_TYPE_INSULATION },
  { value: "siding", label: COPY.JOB_TYPE_SIDING },
  { value: "windows_doors", label: COPY.JOB_TYPE_WINDOWS_DOORS },
  { value: "demolition", label: COPY.JOB_TYPE_DEMOLITION },
  { value: "bathroom_reno", label: COPY.JOB_TYPE_BATHROOM_RENO },
  { value: "kitchen_reno", label: COPY.JOB_TYPE_KITCHEN_RENO },
  { value: "basement_finishing", label: COPY.JOB_TYPE_BASEMENT_FINISHING },
  { value: "deck_fence", label: COPY.JOB_TYPE_DECK_FENCE },
  { value: "general_renovation", label: COPY.JOB_TYPE_GENERAL_RENOVATION },
  { value: "fire_restoration", label: COPY.JOB_TYPE_FIRE_RESTORATION },
  { value: "waterproofing", label: COPY.JOB_TYPE_WATERPROOFING },
  { value: "excavation", label: COPY.JOB_TYPE_EXCAVATION },
  { value: "tile_masonry", label: COPY.JOB_TYPE_TILE_MASONRY },
  { value: "carpentry", label: COPY.JOB_TYPE_CARPENTRY },
  { value: "garage_door", label: COPY.JOB_TYPE_GARAGE_DOOR },
  { value: "solar", label: COPY.JOB_TYPE_SOLAR },
  { value: "other", label: COPY.JOB_TYPE_OTHER },
] as const;

// Cost category options for select dropdown
export const COST_CATEGORY_OPTIONS: ReadonlyArray<{
  value: string;
  label: string;
}> = [
  { value: "labour", label: "Labour" },
  { value: "materials", label: "Materials" },
  { value: "subcontractor", label: "Subcontractor" },
  { value: "equipment", label: "Equipment" },
  { value: "other", label: "Other" },
] as const;
